services:
  media-service:
    serviceName: media
    image:
      repository: thanhtien2208/yas-media
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30101

  order-service:
    serviceName: order
    image:
      repository: thanhtien2208/yas-order
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30102

  product-service:
    serviceName: product
    image:
      repository: thanhtien2208/yas-product
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30103

  cart-service:
    serviceName: cart
    image:
      repository: thanhtien2208/yas-cart
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30104

  rating-service:
    serviceName: rating
    image:
      repository: thanhtien2208/yas-rating
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30105

  customer-service:
    serviceName: customer
    image:
      repository: thanhtien2208/yas-customer
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30106

  location-service:
    serviceName: location
    image:
      repository: thanhtien2208/yas-location
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30107

  inventory-service:
    serviceName: inventory
    image:
      repository: thanhtien2208/yas-inventory
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30108

  tax-service:
    serviceName: tax-service
    image:
      repository: thanhtien2208/yas-tax
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30109

  search-service:
    serviceName: search
    image:
      repository: thanhtien2208/yas-search
      tag: v1.0.0
    containerPort: 8080
    nodePort: 30110
