tax-service:
  serviceName: tax
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-tax
    tag: main
  containerPort: 8080
  nodePort: 30001
  resources:
    limits:
      memory: "512Mi"
    requests:
      memory: "256Mi"
  initialDelaySeconds: 40
  useElastic: false
  useKafka: false

order-service:
  serviceName: order
  replicaCount: 1
  image:
    repository: thanhtien2208/yas-order
    tag: main
  containerPort: 8085
  readinessPath: /order/actuator/health
  nodePort: 30002
  resources:
    limits:
      memory: "512Mi"
    requests:
      memory: "256Mi"
  initialDelaySeconds: 80
  useKafka: true
  useElastic: false

media-service:
  serviceName: media
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-media
    tag: main
  containerPort: 8080
  nodePort: 30003
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"
  initialDelaySeconds: 40
  useElastic: false
  useKafka: false

product-service:
  serviceName: product
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-product
    tag: main
  containerPort: 8080
  nodePort: 30004
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"
  initialDelaySeconds: 40
  useElastic: false
  useKafka: false

cart-service:
  serviceName: cart
  replicaCount: 1
  image:
    repository: thanhtien2208/yas-cart
    tag: main
  containerPort: 8084
  readinessPath: /cart/actuator/health
  nodePort: 30005
  resources:
    limits:
      memory: "512Mi"
    requests:
      memory: "256Mi"
  initialDelaySeconds: 40
  useElastic: false
  useKafka: false

rating-service:
  serviceName: rating
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-rating
    tag: main
  containerPort: 8080
  nodePort: 30006
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"
  initialDelaySeconds: 40
  useElastic: false
  useKafka: false

customer-service:
  serviceName: customer
  replicaCount: 1
  image:
    repository: thanhtien2208/yas-customer
    tag: main
  containerPort: 8080
  nodePort: 30007
  resources:
    limits:
      memory: "512Mi"
    requests:
      memory: "256Mi"
  initialDelaySeconds: 40
  useElastic: false
  useKafka: false

location-service:
  serviceName: location
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-location
    tag: main
  containerPort: 8086
  readinessPath: /location/actuator/health
  nodePort: 30008
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"
  initialDelaySeconds: 100
  useKafka: true
  useElastic: false

inventory-service:
  serviceName: inventory
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-inventory
    tag: main
  containerPort: 8080
  nodePort: 30009
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"
  initialDelaySeconds: 40
  useKafka: true
  useElastic: false

search-service:
  serviceName: search
  replicaCount: 0
  image:
    repository: thanhtien2208/yas-search
    tag: main
  containerPort: 8092
  readinessPath: /search/actuator/health
  nodePort: 30010
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"
  initialDelaySeconds: 180
  useElastic: true
  useKafka: true
