apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.serviceName } }
  labels:
    app: { { .Values.serviceName } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.serviceName } }
  template:
    metadata:
      labels:
        app: { { .Values.serviceName } }
    spec:
      containers:
        - name: { { .Values.serviceName } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.containerPort } }
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: { { .Values.resources.limits.memory } }
              cpu: { { .Values.resources.limits.cpu } }
            requests:
              memory: { { .Values.resources.requests.memory } }
              cpu: { { .Values.resources.requests.cpu } }
          readinessProbe:
            httpGet:
              path: { { .Values.readinessPath } }
              port: { { .Values.containerPort } }
            initialDelaySeconds: { { .Values.initialDelaySeconds } }
            periodSeconds: 10
