{{- range $key, $val := .Values }}
{{- if kindIs "map" $val }}
{{- if $val.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $val.serviceName }}
  labels:
    app: {{ $val.serviceName }}
spec:
  replicas: {{ $val.replicaCount }}
  selector:
    matchLabels:
      app: {{ $val.serviceName }}
  template:
    metadata:
      labels:
        app: {{ $val.serviceName }}
    spec:
      containers:
        - name: {{ $val.serviceName }}
          image: "{{ $val.image.repository }}:{{ $val.image.tag }}"
          ports:
            - containerPort: {{ $val.containerPort }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: {{ $val.resources.limits.memory }}
              cpu: {{ $val.resources.limits.cpu }}
            requests:
              memory: {{ $val.resources.requests.memory }}
              cpu: {{ $val.resources.requests.cpu }}
          readinessProbe:
            httpGet:
              path: {{ $val.readinessPath }}
              port: {{ $val.containerPort }}
            initialDelaySeconds: {{ $val.initialDelaySeconds }}
            periodSeconds: 10
---
{{- end }}
{{- end }}
{{- end }}