apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
spec:
  type: NodePort
  selector:
    app: "{{ .Values.serviceName }}"
  ports:
    - protocol: TCP
      port: "{{ .Values.containerPort }}"
      targetPort: "{{ .Values.containerPort }}"
      nodePort: "{{ .Values.nodePort }}"
