apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-config
  namespace: dev
data:
  init-databases.sql: |
    CREATE DATABASE cart;
    CREATE DATABASE "order";
    CREATE DATABASE search;
    CREATE DATABASE inventory;
    CREATE DATABASE customer;
    CREATE DATABASE media;
    CREATE DATABASE product;
    CREATE DATABASE rating;
    CREATE DATABASE location;
    CREATE DATABASE tax;
