apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: dev
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: yasadminuser
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: dev
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql
