apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-environment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/tiennt220805/My-DevOps-YAS-Config.git"
    targetRevision: HEAD
    path: yas-helm-chart
    helm:
      valueFiles:
        - ../environments/values-staging.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
